# Generated by Django 3.1 on 2021-01-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=30)),
                ('song_url', models.CharField(max_length=400)),
                ('song_genre', models.CharField(choices=[('', 'Select Genre'), ('0', '가요'), ('1', 'R&B'), ('2', 'POP'), ('3', 'JAZZ'), ('4', '인디음악'), ('5', '댄스'), ('6', '랩/힙합'), ('7', '기타')], max_length=128)),
                ('song_tag', models.CharField(choices=[('', 'Select Tag'), ('0', '탈주'), ('1', '비오는날'), ('2', '노동요'), ('3', '심신안정,ASMR'), ('4', '현실도피'), ('5', '에러뜰때'), ('6', '드라이브')], max_length=128)),
                ('song_start', models.CharField(max_length=100, null=True)),
                ('song_end', models.CharField(max_length=100, null=True)),
                ('song_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('song_detail', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_title', models.CharField(max_length=200)),
                ('play_list', models.CharField(max_length=200)),
                ('play_detail', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
