# Generated by Django 3.1 on 2020-08-31 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='song_tag',
            field=models.CharField(choices=[('', 'Select Tag'), ('0', '탈주'), ('1', '비오는날'), ('2', '노동요'), ('3', '심신안정,ASMR'), ('4', '현실도피'), ('5', '에러뜰때'), ('6', '드라이브')], max_length=128),
        ),
    ]
